// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ioxvwidlnkeqmetobszm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlveHZ3aWRsbmtlcW1ldG9ic3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTU0NTUsImV4cCI6MjA2MzI5MTQ1NX0.lv-RY-pPuavCCpKAJcZFGi-iLe3CucNHuEkQsXOyh0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);